### ISSUE TITLE
Error in running the code

### ISSUE THREAD

**Issue by Harivallabha** [bmazoure/DRIML#1]
Cloned the repo, and ran `python main.py --lambda_LL "0" --lambda_GL "0" --lambda_LG "0" --lambda_GG "1" --experiment-name "test" --env-name "procgen-bigfish-v0.500" --n_step-return "7" --nce-batch-size "256" --horizon "10000" --algo "c51" --n-cpus "8" --n-gpus "1" --weight-save-interval "-1" --n_step-nce "-2" --frame_stack "3" --nce_loss "InfoNCE_action_loss" --log-interval-steps=1000 --mode "serial"` as given in the README.md

Runs into the following type error: `TypeError: seed() takes 1 positional argument but 2 were given`

Here's the complete stack trace: Traceback (most recent call last):
  File "main.py", line 223, in <module>
    config=config
  File "main.py", line 176, in build_and_train
    runner.train()
  File "/home/hari/Desktop/Hari//MILA/rlpyt/rlpyt/runners/minibatch_rl.py", line 301, in train
    n_itr = self.startup()
  File "/home/hari/Desktop/Hari//MILA/rlpyt/rlpyt/runners/minibatch_rl.py", line 81, in startup
    world_size=world_size,
  File "/home/hari/Desktop/Hari/MILA/rlpyt/rlpyt/samplers/serial/sampler.py", line 46, in initialize
    set_envs_seeds(envs, seed)  # Random seed made in runner.
  File "/home/hari/Desktop/Hari/MILA/rlpyt/rlpyt/utils/seed.py", line 61, in set_envs_seeds
    env.seed(seed + i)
  File "/home/hari/anaconda3/envs/RAD/lib/python3.7/site-packages/gym/core.py", line 241, in seed
    return self.env.seed(seed)
  File "/home/hari/anaconda3/envs/RAD/lib/python3.7/site-packages/gym/core.py", line 241, in seed
    return self.env.seed(seed)
TypeError: seed() takes 1 positional argument but 2 were given

Seems to be a bug in the codebase unless I'm mistaken. Any thoughts as to how I may resolve this is appreciated.

**Comment by bmazoure** [comment]
Try commenting out line 215 in main.py - it will run and set a random sampler seed instead.

**Comment by Harivallabha** [comment]
Tried that; Throws up the same error.

**Comment by bmazoure** [comment]
Pushed an update that should have fixed it under latest rlpyt version. For future: this happened because rlpyt requires a set_seet method for all envs (for now discarded for Procgen, but can be changed under scripts/rlpyt_override.py).
